config/routes.rb
Rails.application.routes.draw do
  root 'reviews#index'
  devise_scope :user do
    get "/users/bias" => "registrations#bias"
  end
  get 'reviews/bias' => 'registrations#bias'
  get 'contributor_info' => 'reviews#info'
  get 'mobile' => 'cities#mobile_test'
  resources :cities, only: [:index, :update, :create]
  resources :reviews
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :show, :edit, :update]

  post 'cities/popup' => 'cities#popup'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Durian beta</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>
  <body>
    <% flash.each do |key, value| %>
    <div class="flash flash <%= key %>">
        <% if (value.kind_of?(Array)) %>
          <% value.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
          <% end %>
        <% else %>
          <%= value %>
        <% end %>
    </div>
    <%- end -%>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Durian beta</a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
            <li><%= link_to 'Write Review', new_review_path %></li>
          <% if current_user %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>



    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </body>
</html>